### ISSUE TITLE
Erorrs while scannning

### ISSUE THREAD

**Issue by useragent23253** [cold-try/Gank-RECON#2]
python3 core.py 

      (
       \                      
        )     __
##-------->  / _`  /\  |\ | |__/
        )    \__> /~~\ | \| |  \  recon.
       /
      (
    
By zhero_ / Twitter @uthor : @blank_cold

------------------------------------------

Enter the targeted domain : google.com

Do you want to use the brute-force method? If yes enter < y > : y

Do you want to scan the ports? If yes enter < y > : y
For the most popular ports enter < p > , for a deeper scan enter any other letter (can be longer or shorter depending on the number of subdomains found) : p

Do you want to check if 403/401 responses are bypassable? If yes enter < y > : y

----------------------------------------

Recovery of the latest version of chromedriver (dl/cache)...
Traceback (most recent call last):
  File "core.py", line 49, in <module>
    findings = google_dork_sub(target)
  File "/root/Scanners/Gank-RECON/subdo_google_dork.py", line 30, in google_dork_sub
    driver = webdriver.Chrome(service=service, options=options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/110.0.5481.77/chromedriver unexpectedly exited. Status code was: 127

Is is working without api?

**Comment by useragent23253** [comment]
If try scanning with api keys 

`Enter the targeted domain : google.com

Do you want to use the brute-force method? If yes enter < y > : y

Do you want to scan the ports? If yes enter < y > : y
For the most popular ports enter < p > , for a deeper scan enter any other letter (can be longer or shorter depending on the number of subdomains found) : p

Do you want to check if 403/401 responses are bypassable? If yes enter < y > :  

----------------------------------------

Recovery of the latest version of chromedriver (dl/cache)...
Traceback (most recent call last):
  File "core.py", line 49, in <module>
    findings = google_dork_sub(target)
  File "/root/Scanners/Gank-RECON/subdo_google_dork.py", line 30, in google_dork_sub
    driver = webdriver.Chrome(service=service, options=options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/110.0.5481.77/chromedriver unexpectedly exited. Status code was: 127`

**Comment by cold-try** [comment]
Hi.
Yes the tool can work without API - as stated in the README -, this error message has nothing to do with that, it is rather a problem with Selenium.

Do you have Chrome installed on your Linux machine? And if so, is it installed in its default location?

**Comment by useragent23253** [comment]
I've installed chromium, same thing, i guess
/usr/bin/chromium-browser, but problem wasn't solve. Also i have only cli on my virtual machine or is not important?

**Comment by useragent23253** [comment]
appriciated, bro. it's working
