### ISSUE TITLE
issue Recovery of the latest version of chromedriver (dl/cache)...

### ISSUE THREAD

**Issue by Az0x7** [cold-try/Gank-RECON#5]
Traceback (most recent call last):
  File "/home/mo/Gank-RECON/core.py", line 58, in <module>
    findings = google_dork_sub(target)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mo/Gank-RECON/subdo_google_dork.py", line 33, in google_dork_sub
    driver = webdriver.Chrome(service=service, options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 277, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 370, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 113
Current browser version is 112.0.5615.138 with binary path /usr/bin/chromium
Stacktrace:
#0 0x55b9acb99133 <unknown>
#1 0x55b9ac8cd966 <unknown>
#2 0x55b9ac8fb5ec <unknown>
#3 0x55b9ac8f68da <unknown>
#4 0x55b9ac8f307b <unknown>
#5 0x55b9ac9329ad <unknown>
#6 0x55b9ac93218f <unknown>
#7 0x55b9ac9299a3 <unknown>
#8 0x55b9ac8fe46a <unknown>
#9 0x55b9ac8ff55e <unknown>
#10 0x55b9acb58cae <unknown>
#11 0x55b9acb5c8fe <unknown>
#12 0x55b9acb65f20 <unknown>
#13 0x55b9acb5d923 <unknown>
#14 0x55b9acb30c0e <unknown>
#15 0x55b9acb80b08 <unknown>
#16 0x55b9acb80c97 <unknown>
#17 0x55b9acb91113 <unknown>
#18 0x7faf96be7fd4 <unknown>

**Comment by cold-try** [comment]
1. It is necessary - in order for chromedriver to work - to have Chrome or Chromium on your machine.

2. If you are on a linux machine it may be necessary to install the libnss3 package (as stated in the README):

sudo apt-get install libnss3

**Comment by Az0x7** [comment]
thanks but libnss3 install i work on vbs
